#Create Directories

#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/
#mkdir /u/flashscratch/j/jmooney3/allSitesPerSpecies
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/IndivFiles
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/logfiles
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/ComputeRelatedness
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/master_vcfClare
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/VEP
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/VEP/parseVEP
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/VEP/HTML
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/Reference_Files/WildDog
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/RecodedVCF
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/RecodedVCF/GenotypeOnly
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/vcfToolsROH
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/vcfToolsROH/AnnotateROH
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/vcfToolsROH/AnnotateROH/AnnotatedRange
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/vcfToolsROH/AnnotateROH/AnnotatedRange/SplitByIndivAndChrom
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/vcfToolsROH/AnnotateROH/AnnotatedRange/SplitByIndivAndChrom_1MbGreater
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/Reference_Files/CanFam3.1_gerpScoresDogProjClare/
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/AnnotateGT
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/AnnotateGT/AllChroms
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/ROHPermutation/
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/ROHPermutation/AnnotationFiles
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/ComputePi
#mkdir /u/flashscratch/j/jmooney3/AllSitesFiles/SubsetN6
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/slidingWindow
#mkdir /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/pairwiseFst 
#mkdir /u/flashscratch/j/jmooney3/pairwiseFst/
