####Grab the scaled gerp score generated by Kirk for Clare's PNAS paper
#The positions in this file are mapped to hg19

#awk '{print $1"\t"$2"\t"$4}' /u/home/j/jmooney3/klohmueldata/share_folder/clare_phylop_pnas/final_GERP_scores.no_scale_rate.txt > /u/home/j/jmooney3/klohmueldata/jazlyn_data/Reference_Files/CanFam3.1_gerpScoresDogProjClare/gerpScores_hg19_MarsdenPNAS.txt


####Generate bed file for all the positions in the canid master file 
#These will be dropped into liftover 

#zcat /u/home/j/jmooney3/klohmueldata/jazlyn_data/DogProject_Clare/master_vcfClare/masterFile_allChroms.vcf.gz | grep -v "#" | awk '{print $1"\t"$2-1"\t"$2}' > /u/home/j/jmooney3/klohmueldata/jazlyn_data/Reference_Files/CanFam3.1_gerpScoresDogProjClare/masterFile_allChroms_CanFam3.bed

####Run liftover from canFam 3.1 to hg19

##!/bin/bash
##$ -cwd
##$ -V
##$ -N runLiftOver
##$ -l time=20:00:00,h_data=7G
##$ -M eplau
##$ -m bea


#/u/home/j/jmooney3/klohmueldata/clares_data/software/lift_over/liftOver masterFile_allChroms_CanFam3.bed /u/home/j/jmooney3/klohmueldata/clares_data/software/lift_over/canFam3.hg19.all.chain.gz liftedOver_masterFileCanFam3.hg19.bed unlifted.bed

####Figure out which positions were successfully lifted over
#The order of the input files matters, must be this order

#awk 'NR==FNR {exclude[$0];next} !($0 in exclude)' unlifted.bed masterFile_allChroms_CanFam3.bed > masterFile_allChroms_CanFam3_successfulLiftOver.bed

####Make a combination file with all the successfully lifted over positions with the canFam 3 (1-based pos, like vcf) and the hg19 (1-based position) 

#paste masterFile_allChroms_CanFam3_successfulLiftOver.bed  liftedOver_masterFileCanFam3.hg19.bed | awk '{print $1"\t"$3"\t"$4"\t"$6}' | sed -e 1i'CHROM_canfam3\tPOS_canfam3\tCHROM_hg19\tPOS_hg19' > masterFileCanFam3_LiftOverhg19_combo.txt

####Add the Gerp score onto the combination file
#I manually changed the header line after generating the file

#awk 'FNR==NR{a[$1,$2]=$3;next}{print $0,a[$3,$4]?a[$3,$4]:"NA"}' gerpScores_hg19_MarsdenPNAS.txt masterFileCanFam3_LiftOverhg19_combo.txt > masterFileCanFam3_LiftOverhg19_comboPlusGerpScore.txt

	##***note I tarballed and zipped all the original files into this folder: inputFilesGerpScore.tar.gz ***##

####Last step is splitting up the file by chromosome

#for f in {1..38};do awk '{print $1"\t"$2"\t"$5}' masterFileCanFam3_LiftOverhg19_comboPlusGerpScore.txt | grep "chr$f" | awk '{print $2"\t"$3}' > reformatForAnnotation_chr"$f".txt ;done
